services:
  db:
    image: postgres:16
    container_name: music-db
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music
    ports:
      - "5432:5432"   # 왼쪽이 내 PC 포트, 오른쪽이 컨테이너 포트
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
