spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/music
    username: music
    password: music
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 캐시 설정
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60s

# 서버 포트 설정 (8080 충돌 해결)
server:
  port: 9090

# Swagger/OpenAPI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  # 서버 목록 설정 (중요!)
  servers:
    - url: http://localhost:9090
      description: 로컬 개발 서버

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,caches
  endpoint:
    health:
      show-details: when-authorized